### ISSUE TITLE
Theme page thumbnail borders

### ISSUE THREAD

**Issue by codebrainz** [geany/www.geany.org#13]
Now that #5 is merged and I can see it in the browser, I wonder if it would be possible to improve the image borders, like maybe:

```html
<img ... class="... border border-secondary rounded" />
```

Or something like that? It will probably make the one (@kugel-) with the "screenshot missing" image look terrible, but seems like it would improve the other thumbnails, especially light themes on the light page background. Eventually I'll get around to making a screenshot for the one that's missing.

What do you think?

**Comment by eht16** [comment]
Well, adding CSS classes is easy :).
Do the mentioned classes exist somewhere or were they just meant as example?

Bootstrap provides a few: https://getbootstrap.com/docs/3.3/css/#images, though not sure if this is what you mean. Currently, we use `img-thumbnail`.

**Comment by codebrainz** [comment]
I got them from [here](https://getbootstrap.com/docs/4.3/utilities/borders/), forgetting that we're using the older Bootstrap version. I don't see any direct equivalent pre-made classes for Bootstrap 3.

**Comment by eht16** [comment]
The screenshot shows the images with the BS3 class `img-rounded`. I think this comes close.
Alternatively, we can add our own class for rounded borders based on the BS4 one (until someone does #9).

![website_themes_rounded_corners](https://user-images.githubusercontent.com/617017/60628743-570ab500-9de2-11e9-84f2-a48866c206ab.png)

**Comment by codebrainz** [comment]
The main thing IMO is to have a distinctive border between between the thumbnails and the light background. My CSS is a little rusty but I think like `border: 1px solid #333;` (or whatever colour) would do it. The rounded corners look cool too though :)

**Comment by eht16** [comment]
Ok, following is the result with your `1px border` suggestion.
![website_themes_rounded_corners_border](https://user-images.githubusercontent.com/617017/60686960-2a66a400-9e9b-11e9-94a2-37f3105971ec.png)

I think this is a bit broad border. I tried using a `box-shadow` instead:
![website_themes_rounded_corners_shadow](https://user-images.githubusercontent.com/617017/60686986-49fdcc80-9e9b-11e9-86ee-432b17550efd.png)

Code used: `box-shadow: 0px 0px 3px 1px rgba(0, 0, 0, 0.5);`

**Comment by codebrainz** [comment]
Agree the box shadow one looks better.

**Comment by codebrainz** [comment]
Thanks @eht16!
