### ISSUE TITLE
Mixed content when accessed through HTTPS

### ISSUE THREAD

**Issue by genodeftest** [geany/www.geany.org#2]
When accessing https://www.geany.org or any other subdomain via HTTPS I get mixed content. It is not recommended to do so. How about using protocol-relative URLs like `//www.geany.org` instead of `http://www.geany.org`?

**Comment by eht16** [comment]
Yup, will do soon.
Currently, the full http-URL comes from Mezzanine (CMS) but can be configured.
I'll change this soon, see #1 for more details on the roadmap.

**Comment by genodeftest** [comment]
This issue seems to be fixed. Thank you!
