### ISSUE TITLE
Downloading all tags from wiki broken

### ISSUE THREAD

**Issue by mooreye** [geany/www.geany.org#43]
On the site
https://wiki.geany.org/tags/start
There is a link to download all tags
https://wiki.geany.org/get_tags
However, it returns:
```
A problem occurred in a Python script.

/tmp/tmpw4hx8uyp.html contains the description of this error.
```

**Comment by eht16** [comment]
Fixed. Sorry for the inconvenience.

Someone forgot to update the "get_tags" script when migrating from Python 2 to 3.

**Comment by mooreye** [comment]
> Fixed. Sorry for the inconvenience.
> 
> Someone forgot to update the "get_tags" script when migrating from Python 2 to 3.

Doesn't seem to work properly. For example, JavaScript tags
https://wiki.geany.org/tags/start#javascript_tags
are not included.

Does it download only tags that are hosted on geany.org? If so, it should say so.

**Comment by eht16** [comment]
As you assumed, the download script consider only tags files which are attached to the wiki page.

I added a note trying to explain it. If you think it could be better, feel free to edit. It's a wiki.
