### ISSUE TITLE
[Documentation] Please specify which programming languages are permissible for geany on https://www.geany.org/support/plugins/

### ISSUE THREAD

**Issue by rubyFeedback** [geany/www.geany.org#45]
Please specify which programming languages are permissible for geany on https://www.geany.org/support/plugins/.

Currently the website there does not mention this. I assume C is one permissive language here, but what about
ruby or python or lua? It would be kind of neat to write add-ons in such languages; I am quite ok with ruby and I
could re-use a LOT of code there. Python users probably feel the same, so specifying this on the homepage
would be useful, I think.

**Comment by eht16** [comment]
Before the first anniversary of this issue, here we go: #46.
