### ISSUE TITLE
Add Geany-Themes gallery page to main website

### ISSUE THREAD

**Issue by suntong** [geany/www.geany.org#5]
Thanks for providing screenshots, but please add previews to them, so that people can see what they are without even install the whole theme package, because after all, it'll be only a single theme that most people will stick to, or at most one or two. 

I can add such preview, if you welcome such PR.

**Comment by eht16** [comment]
Nice, this sounds like fun :).
I would implement server-side to avoid depending on JS unnecessarily.

**Comment by suntong** [comment]
I was indeed preparing to add preview to the screenshots folder for people to easily preview, I'll do it any way, because comparing to server-side implementation, my approach is super simple. I'll do it and post back... 

Not objecting server-side implementation, just want to KISS, since such preview seldom needs update.

**Comment by suntong** [comment]
Done, please check out https://github.com/geany/geany-themes/pull/30 and
https://github.com/suntong/geany-themes/tree/master/screenshots#darculapng

Please note that individual screenshot can be directly linked in url, e.g. I like 
https://github.com/suntong/geany-themes/tree/master/screenshots#sleepy-pastelpng

and the title links to the individual screenshot as well, if someone prefer just to see one screenshot. 

I'll explain how I did it next, it is semi-automatic, and again, super easy.

**Comment by suntong** [comment]
> I'll explain how I did it next, it is semi-automatic, and again, super easy.

https://dev.to/suntong/generating-image-preview-easily-opj

and very easy to customize the result too.
