### ISSUE TITLE
Link to irclog.py is dead

### ISSUE THREAD

**Issue by andy5995** [geany/www.geany.org#7]
The link to 'irclog.py' is dead.

https://irc.geany.org/logs/log_20190621.html

See the bottom line:
`Stats generated by irclog.py on Fri Jun 21 23:58:01 2019 (times in UTC, will be generated every 24 hours)`

Me and @elextr couldn't figure out how to fix it.

**Comment by elextr** [comment]
@elextr can't even figure out where it comes from. :sheep: :grin:

**Comment by eht16** [comment]
The script is back in place.
I cannot say why it was missing and for how long, maybe I deleted it accidentally or so.
If so, sorry.

**Comment by eht16** [comment]
Ah, and I probably will add it to the https://github.com/geany/infrastructure repository as well.
